App\Entity\Book: # Namespace de la entidad
  attributes:
    id:
      groups: [ 'book' ]
    title:
      groups: [ 'book' ]
    image:
      groups: [ 'book' ]
    categories:
      groups: [ 'book' ]
    author:
      groups: [ 'book' ]