<?php

namespace Container6IExBUG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MWs7J1zService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MWs7J1z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MWs7J1z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authorManager' => ['privates', 'App\\Service\\AuthorManager', 'getAuthorManagerService', true],
        ], [
            'authorManager' => 'App\\Service\\AuthorManager',
        ]);
    }
}
