<?php

namespace Container045c5am;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HP_EWPxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hP.EWPx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hP.EWPx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bookManager' => ['privates', 'App\\Service\\BookManager', 'getBookManagerService', true],
        ], [
            'bookManager' => 'App\\Service\\BookManager',
        ]);
    }
}
