<?php

namespace Container045c5am;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6O_GRwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6_O.gRw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6_O.gRw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Api\\AuthorController::getActions' => ['privates', '.service_locator.MWs7J1z', 'get_ServiceLocator_MWs7J1zService', true],
            'App\\Controller\\Api\\AuthorController::setViewHandler' => ['privates', '.service_locator.dHHQDtH', 'get_ServiceLocator_DHHQDtHService', true],
            'App\\Controller\\Api\\BooksController::deleteAction' => ['privates', '.service_locator.hP.EWPx', 'get_ServiceLocator_HP_EWPxService', true],
            'App\\Controller\\Api\\BooksController::editAction' => ['privates', '.service_locator.J5blmtX', 'get_ServiceLocator_J5blmtXService', true],
            'App\\Controller\\Api\\BooksController::getActions' => ['privates', '.service_locator.hP.EWPx', 'get_ServiceLocator_HP_EWPxService', true],
            'App\\Controller\\Api\\BooksController::getBookDetailActions' => ['privates', '.service_locator.hP.EWPx', 'get_ServiceLocator_HP_EWPxService', true],
            'App\\Controller\\Api\\BooksController::postAction' => ['privates', '.service_locator.J5blmtX', 'get_ServiceLocator_J5blmtXService', true],
            'App\\Controller\\Api\\BooksController::setViewHandler' => ['privates', '.service_locator.dHHQDtH', 'get_ServiceLocator_DHHQDtHService', true],
            'App\\Controller\\Api\\CategoryController::getActions' => ['privates', '.service_locator.GZ5HSon', 'get_ServiceLocator_GZ5HSonService', true],
            'App\\Controller\\Api\\CategoryController::postAction' => ['privates', '.service_locator.GZ5HSon', 'get_ServiceLocator_GZ5HSonService', true],
            'App\\Controller\\Api\\CategoryController::setViewHandler' => ['privates', '.service_locator.dHHQDtH', 'get_ServiceLocator_DHHQDtHService', true],
            'App\\Controller\\BookController::createBook' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\BookController::getBookById' => ['privates', '.service_locator.2vrAr7L', 'get_ServiceLocator_2vrAr7LService', true],
            'App\\Controller\\BookController::listBooks' => ['privates', '.service_locator.2vrAr7L', 'get_ServiceLocator_2vrAr7LService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\Api\\AuthorController:getActions' => ['privates', '.service_locator.MWs7J1z', 'get_ServiceLocator_MWs7J1zService', true],
            'App\\Controller\\Api\\AuthorController:setViewHandler' => ['privates', '.service_locator.dHHQDtH', 'get_ServiceLocator_DHHQDtHService', true],
            'App\\Controller\\Api\\BooksController:deleteAction' => ['privates', '.service_locator.hP.EWPx', 'get_ServiceLocator_HP_EWPxService', true],
            'App\\Controller\\Api\\BooksController:editAction' => ['privates', '.service_locator.J5blmtX', 'get_ServiceLocator_J5blmtXService', true],
            'App\\Controller\\Api\\BooksController:getActions' => ['privates', '.service_locator.hP.EWPx', 'get_ServiceLocator_HP_EWPxService', true],
            'App\\Controller\\Api\\BooksController:getBookDetailActions' => ['privates', '.service_locator.hP.EWPx', 'get_ServiceLocator_HP_EWPxService', true],
            'App\\Controller\\Api\\BooksController:postAction' => ['privates', '.service_locator.J5blmtX', 'get_ServiceLocator_J5blmtXService', true],
            'App\\Controller\\Api\\BooksController:setViewHandler' => ['privates', '.service_locator.dHHQDtH', 'get_ServiceLocator_DHHQDtHService', true],
            'App\\Controller\\Api\\CategoryController:getActions' => ['privates', '.service_locator.GZ5HSon', 'get_ServiceLocator_GZ5HSonService', true],
            'App\\Controller\\Api\\CategoryController:postAction' => ['privates', '.service_locator.GZ5HSon', 'get_ServiceLocator_GZ5HSonService', true],
            'App\\Controller\\Api\\CategoryController:setViewHandler' => ['privates', '.service_locator.dHHQDtH', 'get_ServiceLocator_DHHQDtHService', true],
            'App\\Controller\\BookController:createBook' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\BookController:getBookById' => ['privates', '.service_locator.2vrAr7L', 'get_ServiceLocator_2vrAr7LService', true],
            'App\\Controller\\BookController:listBooks' => ['privates', '.service_locator.2vrAr7L', 'get_ServiceLocator_2vrAr7LService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\Api\\AuthorController::getActions' => '?',
            'App\\Controller\\Api\\AuthorController::setViewHandler' => '?',
            'App\\Controller\\Api\\BooksController::deleteAction' => '?',
            'App\\Controller\\Api\\BooksController::editAction' => '?',
            'App\\Controller\\Api\\BooksController::getActions' => '?',
            'App\\Controller\\Api\\BooksController::getBookDetailActions' => '?',
            'App\\Controller\\Api\\BooksController::postAction' => '?',
            'App\\Controller\\Api\\BooksController::setViewHandler' => '?',
            'App\\Controller\\Api\\CategoryController::getActions' => '?',
            'App\\Controller\\Api\\CategoryController::postAction' => '?',
            'App\\Controller\\Api\\CategoryController::setViewHandler' => '?',
            'App\\Controller\\BookController::createBook' => '?',
            'App\\Controller\\BookController::getBookById' => '?',
            'App\\Controller\\BookController::listBooks' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Api\\AuthorController:getActions' => '?',
            'App\\Controller\\Api\\AuthorController:setViewHandler' => '?',
            'App\\Controller\\Api\\BooksController:deleteAction' => '?',
            'App\\Controller\\Api\\BooksController:editAction' => '?',
            'App\\Controller\\Api\\BooksController:getActions' => '?',
            'App\\Controller\\Api\\BooksController:getBookDetailActions' => '?',
            'App\\Controller\\Api\\BooksController:postAction' => '?',
            'App\\Controller\\Api\\BooksController:setViewHandler' => '?',
            'App\\Controller\\Api\\CategoryController:getActions' => '?',
            'App\\Controller\\Api\\CategoryController:postAction' => '?',
            'App\\Controller\\Api\\CategoryController:setViewHandler' => '?',
            'App\\Controller\\BookController:createBook' => '?',
            'App\\Controller\\BookController:getBookById' => '?',
            'App\\Controller\\BookController:listBooks' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
