createBook:
  path: /api/book
  methods: 'POST'
  controller: App\Controller\BookController::createBook

getBookById:
  path: /api/book/{id}
  methods: 'GET'
  controller: App\Controller\BookController::getBookById