createBook:
  path: /book
  methods: 'POST'
  controller: App\Controller\BookController::createBook

getBookById:
  path: /book/{id}
  methods: 'GET'
  controller: App\Controller\BookController::getBookById